name: "Lint"

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4.1.1"

      - name: "Set up Python"
        uses: "actions/setup-python@v5.0.0"
        with:
          python-version: "3.11"
          cache: "pip"

      - name: "Install requirements"
        run: |
          pip install --constraint=test_requirements.txt ruff

      - name: "Run"
        run: |
          ruff check .
          ruff format --check . 