name: "HACS Validation"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs:
    name: "HACS Validation"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v3"

      - name: "Run HACS Action"
        uses: "hacs/action@main"
        with:
          category: "integration"
          # Optional: You can specify token if needed
          # token: "${{ secrets.GITHUB_TOKEN }}" 